# Useful resource: https://medium.com/@abulka/getting-python-and-wxpython-apps-into-the-ubuntu-app-store-ccca7ae537a3
name: chimpstackr
version: v0.0.16
summary: Focus stacking software
description: |
  ChimpStackr is a program that can be used for focus stacking many images.
  Focus stacking is often a necessity when working with high-magnification pictures.

base: core18
grade: stable # "stable" for release or "devel" when debugging
confinement: strict

architectures:
  - build-on: [amd64]

apps:
  chimpstackr:
    command: bin/snapcraft-preload bin/app
    extensions:
      - kde-neon
    plugs:
      - home
      - removable-media

parts:
  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    build-packages:
      - on amd64:
        - gcc-multilib
        - g++-multilib
    stage-packages:
      - lib32stdc++6
  chimpstackr:
    plugin: python
    source: .
    requirements: ['requirements.txt']
    build-packages:
      - libxkbfile-dev
      - libtbb-dev
    stage-packages:
      - libxkbcommon0
      - libgtk-3-0
      - libxkbfile1
      - gstreamer1.0-gl
      - libtbb2
