# Useful resource: https://medium.com/@abulka/getting-python-and-wxpython-apps-into-the-ubuntu-app-store-ccca7ae537a3

name: chimpstackr
version: v0.0.07 #git
summary: Focus stacking software
description: |
  ChimpStackr is a program that can be used for focus stacking many images.
  Focus stacking is often a necessity when working with high-magnification pictures.

base: core20
grade: candidate # "candidate" for release or "devel" when debugging
confinement: strict

architectures:
  - build-on: [amd64]

apps:
  chimpstackr:
    command: bin/python3 $SNAP/src/run.py
    extensions: 
      - kde-neon
    plugs:
      - home
      - removable-media

parts:
  copy-source-code:
    plugin: dump
    source: ./src
    organize:
      "*": src/
    
  
  chimpstackr:
    plugin: python
    source: .
    requirements: ['requirements.txt']
    build-packages:
      - libxkbfile-dev
      - libtbb-dev
    stage-packages:
      - libxkbcommon0
      - libgtk-3-0
      - libxkbfile1
      - gstreamer1.0-gl
      - libtbb2
      #- appmenu-gtk2-module 
      - appmenu-gtk3-module
    after: [copy-source-code]
