name: chimpstackr
version: git #'0.1'
summary: Free focus stacking software # Max 79 chars
description: |
  Free and open source focus stacking software
  that aims to be a replacement for commercial programs.

base: core20
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: [amd64]

apps:
  chimpstackr:
    #command: chimpstackr # desktop-launch $SNAP/bin/chimpstackr
    command: bin/python3 $SNAP/lib/python3.8/site-packages/src/run.py
    #command: bin/python  $SNAP/bin/run.py
    extensions: 
      - kde-neon
    plugs:
      - home
      - removable-media

parts:
  chimpstackr:
    plugin: python
    source: .
    requirements: ['requirements.txt']
    build-packages:
      - libxkbfile-dev
      - libtbb-dev
    stage-packages:
      - libxkbcommon0
      - libgtk-3-0
      - libxkbfile1
      - gstreamer1.0-gl
      - libtbb2
