name: chimpstackr
title: chimpstackr
base: core20
version: '0.1'
summary: Free focus stacking software # Max 79 char
description: |
  Free and open source focus stacking software
  that aims to be a replacement for commercial programs.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: [amd64]

parts:
  chimpstackr:
    plugin: python
    requirements: ['requirements.txt']
    source: .
    build-packages:
      - libxkbfile-dev
      - libtbb-dev
    stage-packages:
      - libxkbcommon0
      - libgtk-3-0
      - libxkbfile1
      - gstreamer1.0-gl
      - libtbb2

apps:
  chimpstackr:
    command: bin/python  $SNAP/bin/run.py
    extensions: [kde-neon]
    plugs:
      - home
      - removable-media
