# Useful resource: https://medium.com/@abulka/getting-python-and-wxpython-apps-into-the-ubuntu-app-store-ccca7ae537a3

name: chimpstackr
version: git #'0.1'
summary: Free focus stacking software # Max 79 chars
description: |
  Free and open source focus stacking software
  that aims to be a replacement for commercial programs.

base: core20
grade: candidate # 'stable' to release into candidate/stable channels
confinement: strict

architectures:
  - build-on: [amd64]

apps:
  chimpstackr:
    command: bin/python3 $SNAP/src/run.py
    extensions: 
      - kde-neon
    plugs:
      - home
      - removable-media

parts:
  # TODO: Only copy "src" dir??
  copy-source-code:
    plugin: dump
    source: .
  chimpstackr:
    plugin: python
    source: .
    requirements: ['requirements.txt']
    build-packages:
      - libxkbfile-dev
      - libtbb-dev
    stage-packages:
      - libxkbcommon0
      - libgtk-3-0
      - libxkbfile1
      - gstreamer1.0-gl
      - libtbb2
    after: [copy-source-code]
