name: python-stacking-gui
title: python-stacking-gui
base: core20
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Free focus stacking software # Max 79 char
description: |
  Free and open source focus stacking software
  that aims to be a replacement for commercial programs.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: [amd64]

parts:
  python-stacking-gui:
    plugin: python
    requirements: ['requirements.txt']
    source: .

apps:
  python-stacking-gui:
    command: bin/python  $SNAP/bin/run.py
    #command: $SNAP/bin/python-stacking-gui
    extensions: [kde-neon]
    plugs:
      - home
      - removable-media
